import time

class GameIntro:
    def screenWarning():
        print("WARNING!!!    ", end = "")
        time.sleep(.5)
        print("WARNING!!!   ", end = "")
        time.sleep(.5)
        print("WARNING!!!   ", end = "")
        time.sleep(.5)
        print("WARNING!!!   ", end = "")
        time.sleep(.5)
        print("WARNING!!!   ", end = "")
        time.sleep(.5)
        print("WARNING!!!    ", end = "")
        time.sleep(.5)
        print("WARNING!!!\n\n")
        time.sleep(1)
        print("To enjoy this game as intended,  please be sure console window is over 90 characters wide.\n\n")
        time.sleep(2)
        print("<-------------------THIS IS 90 CHARACTERS WIDE - ADJUST YOUR WINDOW NOW------------------>\n\n")
        time.sleep(2)
        input("After window is adjusted, press 'enter' to continue.")

    def gameTitle():
        time.sleep(2)
        print(" \n")
        time.sleep(1)
        print(" \n")
        time.sleep(1)
        print(" \n")
        time.sleep(1) 
        print("Welcome to", end = "")
        time.sleep(1)
        print(".", end = "")
        time.sleep(1)
        print(".", end = "")
        time.sleep(1)
        print(".", end = "")
        time.sleep(1)
        print("")
        time.sleep(1)

        print("     ________  __    __  ________    ________  __    __    ____    _______ ____   ____")
        time.sleep(.1)
        print("    |__    __||  |  |  ||   _____|  /   ____ \|  |  |  | /  __  \ /   ____||   \ /   |")
        time.sleep(.1)
        print("       |  |   |  |__|  ||  |____    |  /    \/|  |__|  |/  /__\  \\\  `---. |  . V .  |")
        time.sleep(.1)
        print("       |  |   |   __   ||   ____|   |  |      |   __   ||   __   | `---.  \|  |\ /|  |")
        time.sleep(.1)
        print("       |  |   |  |  |  ||  |_____   |  \____/\|  |  |  ||  |  |  |/\___/  /|  | V |  |")
        time.sleep(.1)
        print("       \__|   \__|  | / \_____  /   \______  /\__|  | / \__|  | / \____  / \__|   | /")
        time.sleep(.1)
        print("                    |/        |/           |/       |/        |/       |/         |/ ")
        time.sleep(.5)
        print("\n                                              A ", end = "")
        time.sleep(.5)
        print("Text-Based ", end = "")
        time.sleep(.5)
        print("Adventure ", end = "")
        time.sleep(.5)
        print("by ", end = "")
        time.sleep(.5)
        print("Jeremy ", end = "")
        time.sleep(.5)
        print("D. ", end = "")
        time.sleep(.5)
        print("Westfall", end = "")
        time.sleep(1)
        print("")
        time.sleep(1)
        input("\nWhen ready to play, press 'enter'.")
        return
